services:
  web:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: django_web
    restart: always
    environment:
      DJANGO_SETTINGS_MODULE: order.settings
      DEBUG: "0"
    ports:
      - "5555:5555"
    volumes:
      - ./order/db.sqlite3:/app/order/db.sqlite3
      - ./database.sqlt:/app/order/database.sqlt


  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vk_bot
    restart: always
#    volumes:
#      - .:/app
    environment:
      VK_TOKEN: "2222q"
#      GROUP_ID: "${GROUP_ID}"
#      OPENAI_API_KEY: "${OPENAI_API_KEY}"
    depends_on:
      - web
    volumes:
      - ./order/db.sqlite3:/app/order/db.sqlite3
      - ./products:/app/products
      - ./database.sqlt:/app/database.sqlt
