# Generated by Django 4.2.4 on 2025-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bot_proxy_host_bot_proxy_password_bot_proxy_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='text_one_remember',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='text_two_remember',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='interval_first',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='interval_second',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='promt',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bot',
            name='proxy_host',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='proxy_password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='proxy_port',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bot',
            name='proxy_user',
            field=models.TextField(),
        ),
    ]
