# Generated by Django 4.2.4 on 2025-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bot_text_one_remember_bot_text_two_remember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
